analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-arguments: 4
  metrics-exclude:
    - test/**
  rules:
    - prefer-trailing-comma:
        break_on: 3
    - prefer-trailing-comma-for-collection