include: package:surf_lint_rules/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false

analyzer:
  exclude:
    - lib/ui/widgets/app_dismissible.dart
    - lib/data/repository/database/app_database.g.dart
    - test/*
