name: places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: 3.0.0-nullsafety.0
  # SVG image
  flutter_svg: 0.21.0-nullsafety.0
  # Package provides internationalization and localization facilities
  intl: ^0.17.0
  # State provider
  provider: ^5.0.0
  # Wraps platform-specific persistent storage for simple data
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter rules
  surf_lint_rules: any

flutter: 
  uses-material-design: true

  assets:
    - res/
    - res/icons/
    - res/icons/menu/
    - res/icons/other/
    - res/icons/catalog/
    - res/icons/empty_pages/
    - res/icons/tutorial/
    - res/icons/logo/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
