name: places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  # Widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^2.1.0
  # SVG image
  flutter_svg: 0.18.1
  # Package provides internationalization and localization facilities
  intl: ^0.16.1
  # State provider
  provider: ^4.3.2+3
  # Wraps platform-specific persistent storage for simple data
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^2.0.0

flutter: 
  uses-material-design: true

  assets:
    - res/
    - res/icons/
    - res/icons/menu/
    - res/icons/other/
    - res/icons/catalog/
    - res/icons/empty_pages/
    - res/icons/tutorial/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
