name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A Flutter plugin for opening iOS and Android phone settings from an app
  app_settings: ^4.1.0
  # Utility classes to work with asynchronous computations
  async: ^2.6.1
  # Widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^2.1.0
  # A library to show images from the internet and keep them in the cache directory
  cached_network_image: ^3.0.0
  # Cupertino icons
  cupertino_icons: ^1.0.3
  # A powerful Http client for Dart
  dio: ^4.0.0
  # Package to compare objects in Dart w/o == operator & hash code
  equatable: ^2.0.2
  # SVG image
  flutter_svg: ^0.22.0
  # A Flutter plugin which provides easy geocoding
  geocoding: ^2.0.0
  # A Flutter geolocation plugin
  geolocator: ^7.0.3
  # A Flutter plugin for iOS and Android for picking images
  image_picker: ^0.7.5+2
  # Package provides internationalization and localization facilities
  intl: ^0.17.0
  # A flutter plugin to find available maps installed on a device and launch them
  map_launcher: ^2.0.0
  # Library to get MIME type from a file name or a file path and get the file extension from a MIME
  mime_type: ^1.0.0
  # Support for inside scrollview + dragging down to close (showModalBottomSheet cannot)
  modal_bottom_sheet: ^2.0.0
  # A reactive persistence library for Flutter and Dart, built on top of sqlite
  moor: ^4.3.0
  # MVVM-inspired framework with respect for Clean Architecture
  mwwm: ^1.1.0
  # A string-based path manipulation library
  path: ^1.8.0
  # Plugin for getting commonly used locations on host platform file systems
  path_provider: ^2.0.1
  # State provider
  provider: ^5.0.0
  # The stream representation of relations between entities and widget utilities
  relation: ^1.0.0
  # RxDart adds additional capabilities to Dart Streams and StreamControllers
  rxdart: ^0.26.0
  # Wraps platform-specific persistent storage for simple data
  shared_preferences: ^2.0.5
  # Extension package for easy access the MediaQuery sizing info on the build context
  sized_context: ^0.2.1+1
  # Flutter apps depending on this package will contain native sqlite3 libraries
  sqlite3_flutter_libs: ^0.4.3
  # Simple, fast generation of RFC4122 UUIDs
  uuid: ^3.0.4
  # A flutter plugin for displaying yandex maps on iOS and Android
  yandex_mapkit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Provides a concrete way of generating files
  build_runner: ^2.0.3
  # Generates table and dataclasses together with the moor package
  moor_generator: ^4.3.0
  # linter rules
  surf_lint_rules: any

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/icons/
    - res/icons/menu/
    - res/icons/other/
    - res/icons/catalog/
    - res/icons/empty_pages/
    - res/icons/tutorial/
    - res/icons/logo/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
